[project]
name = "automatedemailsubscriptionmodel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pypyodbc>=1.3.6",
]
